POST http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTMwNTUwOTEsInN1YiI6IjkzZmJmMWE3LTdkZjktNGQ1Ny1iYjIyLWQ5ZGI1NDIwMDJjZiJ9.NHgyH4h2VIky5XmY2ttFLoFuzG8WvGdIkamJLK5GOAM
Content-Type: application/json

{
  "name": "My Product",
  "price": 100
}


###

GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTMwNTc0NjYsInN1YiI6IjkzZmJmMWE3LTdkZjktNGQ1Ny1iYjIyLWQ5ZGI1NDIwMDJjZiJ9.XNmcBsPetjAZwkBDEWduvJPiGefEK0PLc0KtG3nfYSI

###

###
GET http://localhost:8000/products/8d096511-9eac-4d6a-8154-e1599f0e0b36 HTTP/1.1

###
PUT http://localhost:8000/products/8d096511-9eac-4d6a-8154-e1599f0e0b36 HTTP/1.1
Content-Type: application/json

{
  "name": "My Product Updated",
  "price": 200
}

###
DELETE http://localhost:8000/products/8d096511-9eac-4d6a-8154-e1599f0e0b36 HTTP/1.1

